### ISSUE TITLE
scm_vegfra option has wrong bounds

### ISSUE THREAD

**Issue by sodoesaburningbus** [wrf-model/Users_Guide#30]
On page 5-118 of the WRF V$ Users Guide, the example value for scm_vegfra is 0.5. This implies a range of [0, 1] for vegetation fraction. In the NOAH Driver module, however, vegetation fraction is divided by 100 (line 772 of module_sf_noahdrv.F); thus the proper bounds are [0,100].

**Comment by kkeene44** [comment]
@sodoesaburningbus 
Thank you so much for bringing this to our attention. As you see, we determined that this was not only incorrect in the Users' Guide, but also in the code. We modified both to reflect that it should be a percentage.
