### ISSUE TITLE
surface irrigation parameterizations in chapt5 with wrong line

### ISSUE THREAD

**Issue by andrewsoong** [wrf-model/Users_Guide#75]
There is a wrong line in WRF-ARW UG V4. sf_surf_irr_schame =1 in line 1 on page 5-54 is repeated . sf_surf_irr_schame=2 could be right. @kkeene44

**Comment by kkeene44** [comment]
@andrewsoong 
Thanks for pointing this out. I've modified this in the repository and [online now](https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/v4.2/users_guide_chap5.html).
