### ISSUE TITLE
Converting WRF Users Guide to text format

### ISSUE THREAD

**Issue by Quba1** [wrf-model/Users_Guide#79]
### Proposed Feature
I propose converting WRF Users Guide into text-based files (eg. `.rst`, `.md` or `.tex`) to allow for easier contributing to the guide. And to make the guide more user-friendly, by for example publishing it in [readthedocs.io](https://readthedocs.org).

### Motivation
WRF is undoubtedly one of the core softwares in community atmospheric modelling. However its documentation is in my opinion the least user-friendly (comparing to eg. MPAS, GSI, MET), and under-developed in some areas (some descriptions of complicated procedures are too basic). Navigation between chapters in online version of the guide is also complicated.
WRF documentation is also spread among several documents (Users Guide, WRF Tutorial, WRF Compiling Tutorial, WRF Best Practices). Because of that working, for example, with WRFDA is very difficult comparing to GSI.
Futhermore, many interesting and important information from WRF/MPAS Workshops is not included in Users Guide, and I believe that would be useful. 

Lately I have been working with the WRF quite a lot, and thus read the Users Guide in detail. And I have found several areas, in which the guide could be improved.
However, as the guide files are in `.doc` format it makes contributing to the guide rather complicated. You need a dedicated software (Ms Word or Libre Office) to edit the files, and text formatting in `.doc` format can sometimes be really annoying task. And then changes are difficult to compare, as Github does not show changes in binary files. So you can't be sure if you didn't accidentaly changed something you didn't want to. And you also can't review what previous commits have changed.

Also, working on text-based files would allow for easier work with community translations of the guide. I have found one fork (by @zhifzhang) of this repository with chinese translation of the guide (they translated five chapters so far) in `.md` format. It would be a shame if that work was lost or not published.

Moreover, if converted to `'.rst` format, the guide could be published on [readthedocs.io](https://readthedocs.org) (similarly to [Model Evaulation Tools Users Guide](https://met.readthedocs.io/en/latest/Users_Guide/index.html)).
That service would make the WRF User Guide more user-friendly, and also **mobile-friendly**. That (or similar) online documentation service also allows for setting up Continuous Deployment - so all community contributions could quickly (and effortlessly) be published. And on readthedocs.io, there is a button "Show on Github" - which would make this repository easier to discover. 

**In my opinion converting the Users Guide into text-based files and publishing it via dedicated online service will help adress all those issues.**

### Additional Info
I am happy to convert the Users Guide myself to the chosen format, prepare it for deployment, and make a pull request. I open this issue to get the opinion of my idea from project owners. Because I don't want my work to be lost if it is not suitable for this project.

**Comment by kkeene44** [comment]
@Quba1 
Thank you so much for your offer and suggestions. Coincidently, our group happens to be in the process of making major modifications to the Users' Guide, which includes a new format that will make it easier to use in GitHub. I'm not sure when everything will be ready, as we just got started and expect it to take some time. It was very kind of you to offer to help us, though. If you have any specific suggestions or corrections to the current Users' Guide, please let us know and we will try to incorporate those changes. Again, thank you!

**Comment by likev** [comment]
I find that the [WRF Users Guide documentation](https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/index.html) is `.rst` format already, please push to GitHub.

**Comment by kkeene44** [comment]
@likev 
That is on my to-do list and I hope to get it on GitHub soon. Thanks!
