### ISSUE TITLE
An error occurred while running wrf.exe ‘free(): invalid pointer’

### ISSUE THREAD

**Issue by dyw770** [wrf-model/Users_Guide#89]
Hi, dear developer, I try to compile WRF and WPS according to the official documents and run a case provided by the official. I successfully compiled WRF and WPS, but a strange error occurred when I ran wrf.exe at the last step of the case. I had this problem on both computers. I don't know how to solve this mistake. I hope I can get your help
![image](https://user-images.githubusercontent.com/26217571/133734671-fa05bfad-2e4b-47b8-aea7-d458125ad853.png)

**Comment by mgduda** [comment]
Please post your question to the WRF Forum at https://forum.mmm.ucar.edu/.
